#!/bin/sh

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

FILES=$(git diff --cached --name-only --diff-filter=ACMR "*.ts" "*.tsx" "*.scss" | sed 's| |\\ |g')
[ -z "$FILES" ] && exit 0

# Format and lint frontend
cd frontend
npm run format 
npm run lint
cd -

# Add back the modified/prettified files to staging
echo "$FILES" | xargs git add

exit 0
