version: "3.7"
services:
    mongo:
        image: "mongo:4.2.3"
        ports: 
            - "27017:27017"
        volumes: 
            - "/tmp/mongo_data:/data/db"
    frontend:
        build: frontend
        ports:
            - "80:80"
    backend:
        build: backend
        ports: 
            - "8000:8000"