# Generated by Django 3.0.4 on 2020-03-21 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('personal_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('team', models.CharField(default='', max_length=50)),
                ('wasSegel', models.BooleanField(default=False, verbose_name='was segel')),
                ('remarks', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='PossibleAvailability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PossibleStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PossibleTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('relevant', models.BooleanField(default=True, verbose_name='relevant')),
                ('people', models.ManyToManyField(related_name='tracks', to='people.Person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PossibleSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('relevant', models.BooleanField(default=True, verbose_name='relevant')),
                ('people', models.ManyToManyField(related_name='subjects', to='people.Person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PossiblePreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('relevant', models.BooleanField(default=True, verbose_name='relevant')),
                ('people', models.ManyToManyField(related_name='preferences', to='people.Person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='person',
            name='availability',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='people.PossibleAvailability'),
        ),
        migrations.AddField(
            model_name='person',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='people.PossibleStatus'),
        ),
    ]
