# Generated by Django 3.0.4 on 2020-03-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('personal_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200)),
            ],
        ),
    ]
